// db/index.ts
// Drizzle client singleton for the Plant Parent local-first SQLite database.
//
// The connection is opened synchronously via expo-sqlite's `openDatabaseSync`,
// and the Drizzle client is created over it. Migrations generated by
// `drizzle-kit generate` are bundled into the app binary (as strings, via
// babel-plugin-inline-import) and applied on first run.
//
// See https://orm.drizzle.team/docs/connect-expo-sqlite for the migration
// bundling pattern and the Expo SDK 56 expo-sqlite API.
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate, useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import { openDatabaseSync } from 'expo-sqlite';

import migrations from './migrations/migrations';
import * as schema from './schema';

/** On-device SQLite database file name. */
export const DATABASE_NAME = 'plant-parent.db';

/**
 * Raw expo-sqlite connection. `enableChangeListener` is required for Drizzle's
 * reactive `useLiveQuery` hook to re-render when the underlying tables change.
 */
export const expoDb = openDatabaseSync(DATABASE_NAME, {
  enableChangeListener: true,
});

/** Type-safe Drizzle client bound to the full schema. */
export const db = drizzle(expoDb, { schema });

export type DB = typeof db;

/**
 * React hook that applies any pending migrations on mount and reports progress.
 * Intended for use in the root layout to gate the app behind a successful
 * migration (returns `{ success, error }`).
 */
export function useMigrationsHook() {
  return useMigrations(db, migrations);
}

/**
 * Imperatively run all pending migrations. Useful outside of React (e.g. in
 * tests or one-off scripts). Resolves once migrations are applied, rejects if
 * a migration fails.
 */
export async function runMigrations(): Promise<void> {
  await migrate(db, migrations);
}
